# -*- coding: utf-8 -*-

import resource

import ctypes
from . import netlink


# H2PY_ERR: h/libmnl/libmnl.h - define: MNL_SOCKET_BUFFER_SIZE = (getpagesize() < 8192L ? getpagesize() : 8192L)
MNL_SOCKET_BUFFER_SIZE	= resource.getpagesize() < 8192 and resource.getpagesize() or 8192

MNL_ALIGNTO = 4
def MNL_ALIGN(len): return (((len)+MNL_ALIGNTO-1) & ~(MNL_ALIGNTO-1))

# H2PY_ERR: h/libmnl/libmnl.h - define: MNL_NLMSG_HDRLEN = MNL_ALIGN(ctypes.sizeof(struct nlmsghdr))
MNL_NLMSG_HDRLEN = MNL_ALIGN(ctypes.sizeof(netlink.Nlmsghdr))

# H2PY_ERR: h/libmnl/libmnl.h - define: MNL_ATTR_HDRLEN = MNL_ALIGN(ctypes.sizeof(struct nlattr))
MNL_ATTR_HDRLEN = MNL_ALIGN(ctypes.sizeof(netlink.Nlattr))


# Generated by h2py from h/libmnl/libmnl.h
MNL_SOCKET_AUTOPID = 0
MNL_TYPE_UNSPEC = 0
MNL_TYPE_U8 = 1
MNL_TYPE_U16 = 2
MNL_TYPE_U32 = 3
MNL_TYPE_U64 = 4
MNL_TYPE_STRING = 5
MNL_TYPE_FLAG = 6
MNL_TYPE_MSECS = 7
MNL_TYPE_NESTED = 8
MNL_TYPE_NESTED_COMPAT = 9
MNL_TYPE_NUL_STRING = 10
MNL_TYPE_BINARY = 11
MNL_TYPE_MAX = 12
MNL_CB_ERROR = -1
MNL_CB_STOP = 0
MNL_CB_OK = 1
SOL_NETLINK = 270
def MNL_ARRAY_SIZE(a): return (ctypes.sizeof(a)/ctypes.sizeof((a)[0]))


### a little bit differ from C macro - requires len
def RING_MSGHDR(hdr, size):
    return ctypes.cast(ctypes.addressof(hdr) + netlink.NL_MMAP_HDRLEN,
                       ctypes.POINTER(ctypes.c_ubyte * size)).contents

MNL_RING_RX = 0
MNL_RING_TX = 1
