# Generated by h2py from ./h/linux/if_addr.h

from __future__ import absolute_import

IFA_UNSPEC = 0
IFA_ADDRESS = 1
IFA_LOCAL = 2
IFA_LABEL = 3
IFA_BROADCAST = 4
IFA_ANYCAST = 5
IFA_CACHEINFO = 6
IFA_MULTICAST = 7
__IFA_MAX = 8
IFA_MAX = (__IFA_MAX - 1)
IFA_F_SECONDARY = 0x01
IFA_F_TEMPORARY = IFA_F_SECONDARY
IFA_F_NODAD = 0x02
IFA_F_OPTIMISTIC = 0x04
IFA_F_DADFAILED = 0x08
IFA_F_HOMEADDRESS = 0x10
IFA_F_DEPRECATED = 0x20
IFA_F_TENTATIVE = 0x40
IFA_F_PERMANENT = 0x80
# H2PY_ERR: ./h/linux/if_addr.h - macro: def IFA_RTA(r): return ((struct rtattr*)(((char*)(r)) + NLMSG_ALIGN(sizeof(struct ifaddrmsg))))
# H2PY_ERR: ./h/linux/if_addr.h - macro: def IFA_PAYLOAD(n): return NLMSG_PAYLOAD(n,sizeof(struct ifaddrmsg))
