# -*- coding: utf-8 -*-


# enum cntl_msg_types
class CtnlMsgTypes(object):
    IPCTNL_MSG_CT_NEW			= 0
    IPCTNL_MSG_CT_GET			= 1
    IPCTNL_MSG_CT_DELETE		= 2
    IPCTNL_MSG_CT_GET_CTRZERO		= 3
    IPCTNL_MSG_CT_GET_STATS_CPU		= 4
    IPCTNL_MSG_CT_GET_STATS		= 5
    IPCTNL_MSG_CT_GET_DYING		= 6
    IPCTNL_MSG_CT_GET_UNCONFIRMED	= 7
    IPCTNL_MSG_MAX			= 8
IPCTNL_MSG_CT_NEW		= CtnlMsgTypes.IPCTNL_MSG_CT_NEW
IPCTNL_MSG_CT_GET		= CtnlMsgTypes.IPCTNL_MSG_CT_GET
IPCTNL_MSG_CT_DELETE		= CtnlMsgTypes.IPCTNL_MSG_CT_DELETE
IPCTNL_MSG_CT_GET_CTRZERO	= CtnlMsgTypes.IPCTNL_MSG_CT_GET_CTRZERO
IPCTNL_MSG_CT_GET_STATS_CPU	= CtnlMsgTypes.IPCTNL_MSG_CT_GET_STATS_CPU
IPCTNL_MSG_CT_GET_STATS		= CtnlMsgTypes.IPCTNL_MSG_CT_GET_STATS
IPCTNL_MSG_CT_GET_DYING		= CtnlMsgTypes.IPCTNL_MSG_CT_GET_DYING
IPCTNL_MSG_CT_GET_UNCONFIRMED	= CtnlMsgTypes.IPCTNL_MSG_CT_GET_UNCONFIRMED
IPCTNL_MSG_MAX			= CtnlMsgTypes.IPCTNL_MSG_MAX

# enum ctnl_exp_msg_types
class CtnlExpMsgTypes(object):
    IPCTNL_MSG_EXP_NEW			= 0
    IPCTNL_MSG_EXP_GET			= 1
    IPCTNL_MSG_EXP_DELETE		= 2
    IPCTNL_MSG_EXP_GET_STATS_CPU	= 3
    IPCTNL_MSG_EXP_MAX			= 4
IPCTNL_MSG_EXP_NEW		= CtnlExpMsgTypes.IPCTNL_MSG_EXP_NEW
IPCTNL_MSG_EXP_GET		= CtnlExpMsgTypes.IPCTNL_MSG_EXP_GET
IPCTNL_MSG_EXP_DELETE		= CtnlExpMsgTypes.IPCTNL_MSG_EXP_DELETE
IPCTNL_MSG_EXP_GET_STATS_CPU	= CtnlExpMsgTypes.IPCTNL_MSG_EXP_GET_STATS_CPU
IPCTNL_MSG_EXP_MAX		= CtnlExpMsgTypes.IPCTNL_MSG_EXP_MAX

# enum ctattr_type
class CtattrType(object):
    CTA_UNSPEC			= 0
    CTA_TUPLE_ORIG		= 1
    CTA_TUPLE_REPLY		= 2
    CTA_STATUS			= 3
    CTA_PROTOINFO		= 4
    CTA_HELP			= 5
    CTA_NAT_SRC			= 6
    CTA_NAT			= CTA_NAT_SRC # backwards compatibility
    CTA_TIMEOUT			= 7
    CTA_MARK			= 8
    CTA_COUNTERS_ORIG		= 9
    CTA_COUNTERS_REPLY		= 10
    CTA_USE			= 11
    CTA_ID			= 12
    CTA_NAT_DST			= 13
    CTA_TUPLE_MASTER		= 14
    CTA_SEQ_ADJ_ORIG		= 15
    CTA_NAT_SEQ_ADJ_ORIG	= CTA_SEQ_ADJ_ORIG
    CTA_SEQ_ADJ_REPLY		= 16
    CTA_NAT_SEQ_ADJ_REPLY	= CTA_SEQ_ADJ_REPLY
    CTA_SECMARK			= 17 # obsolete
    CTA_ZONE			= 18
    CTA_SECCTX			= 19
    CTA_TIMESTAMP		= 20
    CTA_MARK_MASK		= 21
    CTA_LABELS			= 22
    CTA_LABELS_MASK		= 23
    __CTA_MAX			= 24
    CTA_MAX			= (__CTA_MAX - 1)
CTA_UNSPEC		= CtattrType.CTA_UNSPEC
CTA_TUPLE_ORIG		= CtattrType.CTA_TUPLE_ORIG
CTA_TUPLE_REPLY		= CtattrType.CTA_TUPLE_REPLY
CTA_STATUS		= CtattrType.CTA_STATUS
CTA_PROTOINFO		= CtattrType.CTA_PROTOINFO
CTA_HELP		= CtattrType.CTA_HELP
CTA_NAT_SRC		= CtattrType.CTA_NAT_SRC
CTA_NAT			= CtattrType.CTA_NAT
CTA_TIMEOUT		= CtattrType.CTA_TIMEOUT
CTA_MARK		= CtattrType.CTA_MARK
CTA_COUNTERS_ORIG	= CtattrType.CTA_COUNTERS_ORIG
CTA_COUNTERS_REPLY	= CtattrType.CTA_COUNTERS_REPLY
CTA_USE			= CtattrType.CTA_USE
CTA_ID			= CtattrType.CTA_ID
CTA_NAT_DST		= CtattrType.CTA_NAT_DST
CTA_TUPLE_MASTER	= CtattrType.CTA_TUPLE_MASTER
CTA_SEQ_ADJ_ORIG	= CtattrType.CTA_SEQ_ADJ_ORIG
CTA_NAT_SEQ_ADJ_ORIG	= CtattrType.CTA_NAT_SEQ_ADJ_ORIG
CTA_SEQ_ADJ_REPLY	= CtattrType.CTA_SEQ_ADJ_REPLY
CTA_NAT_SEQ_ADJ_REPLY	= CtattrType.CTA_NAT_SEQ_ADJ_REPLY
CTA_SECMARK		= CtattrType.CTA_SECMARK
CTA_ZONE		= CtattrType.CTA_ZONE
CTA_SECCTX		= CtattrType.CTA_SECCTX
CTA_TIMESTAMP		= CtattrType.CTA_TIMESTAMP
CTA_MARK_MASK		= CtattrType.CTA_MARK_MASK
CTA_LABELS		= CtattrType.CTA_LABELS
CTA_LABELS_MASK		= CtattrType.CTA_LABELS_MASK
CTA_MAX			= CtattrType.CTA_MAX

# enum ctattr_tuple
class CtattrTuple(object):
    CTA_TUPLE_UNSPEC	= 0
    CTA_TUPLE_IP	= 1
    CTA_TUPLE_PROTO	= 2
    CTA_TUPLE_ZONE	= 3
    __CTA_TUPLE_MAX	= 4
    CTA_TUPLE_MAX	= (__CTA_TUPLE_MAX - 1)
CTA_TUPLE_UNSPEC	= CtattrTuple.CTA_TUPLE_UNSPEC
CTA_TUPLE_IP		= CtattrTuple.CTA_TUPLE_IP
CTA_TUPLE_PROTO		= CtattrTuple.CTA_TUPLE_PROTO
CTA_TUPLE_ZONE		= CtattrTuple.CTA_TUPLE_ZONE
CTA_TUPLE_MAX		= CtattrTuple.CTA_TUPLE_MAX

# enum ctattr_ip
class CtattrIp(object):
    CTA_IP_UNSPEC	= 0
    CTA_IP_V4_SRC	= 1
    CTA_IP_V4_DST	= 2
    CTA_IP_V6_SRC	= 3
    CTA_IP_V6_DST	= 4
    __CTA_IP_MAX	= 5
    CTA_IP_MAX		= (__CTA_IP_MAX - 1)
CTA_IP_UNSPEC	= CtattrIp.CTA_IP_UNSPEC
CTA_IP_V4_SRC	= CtattrIp.CTA_IP_V4_SRC
CTA_IP_V4_DST	= CtattrIp.CTA_IP_V4_DST
CTA_IP_V6_SRC	= CtattrIp.CTA_IP_V6_SRC
CTA_IP_V6_DST	= CtattrIp.CTA_IP_V6_DST
CTA_IP_MAX	= CtattrIp.CTA_IP_MAX

# enum ctattr_l4proto
class CtattrL4proto(object):
    CTA_PROTO_UNSPEC		= 0
    CTA_PROTO_NUM		= 1
    CTA_PROTO_SRC_PORT		= 2
    CTA_PROTO_DST_PORT		= 3
    CTA_PROTO_ICMP_ID		= 4
    CTA_PROTO_ICMP_TYPE		= 5
    CTA_PROTO_ICMP_CODE		= 6
    CTA_PROTO_ICMPV6_ID		= 7
    CTA_PROTO_ICMPV6_TYPE	= 8
    CTA_PROTO_ICMPV6_CODE	= 9
    __CTA_PROTO_MAX		= 10
    CTA_PROTO_MAX		= (__CTA_PROTO_MAX - 1)
CTA_PROTO_UNSPEC	= CtattrL4proto.CTA_PROTO_UNSPEC
CTA_PROTO_NUM		= CtattrL4proto.CTA_PROTO_NUM
CTA_PROTO_SRC_PORT	= CtattrL4proto.CTA_PROTO_SRC_PORT
CTA_PROTO_DST_PORT	= CtattrL4proto.CTA_PROTO_DST_PORT
CTA_PROTO_ICMP_ID	= CtattrL4proto.CTA_PROTO_ICMP_ID
CTA_PROTO_ICMP_TYPE	= CtattrL4proto.CTA_PROTO_ICMP_TYPE
CTA_PROTO_ICMP_CODE	= CtattrL4proto.CTA_PROTO_ICMP_CODE
CTA_PROTO_ICMPV6_ID	= CtattrL4proto.CTA_PROTO_ICMPV6_ID
CTA_PROTO_ICMPV6_TYPE	= CtattrL4proto.CTA_PROTO_ICMPV6_TYPE
CTA_PROTO_ICMPV6_CODE	= CtattrL4proto.CTA_PROTO_ICMPV6_CODE
CTA_PROTO_MAX		= CtattrL4proto.CTA_PROTO_MAX

# enum ctattr_protoinfo
class CtattrProtoinfo(object):
    CTA_PROTOINFO_UNSPEC	= 0
    CTA_PROTOINFO_TCP		= 1
    CTA_PROTOINFO_DCCP		= 2
    CTA_PROTOINFO_SCTP		= 3
    __CTA_PROTOINFO_MAX		= 4
    CTA_PROTOINFO_MAX		= (__CTA_PROTOINFO_MAX - 1)
CTA_PROTOINFO_UNSPEC	= CtattrProtoinfo.CTA_PROTOINFO_UNSPEC
CTA_PROTOINFO_TCP	= CtattrProtoinfo.CTA_PROTOINFO_TCP
CTA_PROTOINFO_DCCP	= CtattrProtoinfo.CTA_PROTOINFO_DCCP
CTA_PROTOINFO_SCTP	= CtattrProtoinfo.CTA_PROTOINFO_SCTP
CTA_PROTOINFO_MAX	= CtattrProtoinfo.CTA_PROTOINFO_MAX

# enum ctattr_protoinfo_tcp
class CtattrProtoinfoTcp(object):
    CTA_PROTOINFO_TCP_UNSPEC		= 0
    CTA_PROTOINFO_TCP_STATE		= 1
    CTA_PROTOINFO_TCP_WSCALE_ORIGINAL	= 2
    CTA_PROTOINFO_TCP_WSCALE_REPLY	= 3
    CTA_PROTOINFO_TCP_FLAGS_ORIGINAL	= 4
    CTA_PROTOINFO_TCP_FLAGS_REPLY	= 5
    __CTA_PROTOINFO_TCP_MAX		= 6
    CTA_PROTOINFO_TCP_MAX		= (__CTA_PROTOINFO_TCP_MAX - 1)
CTA_PROTOINFO_TCP_UNSPEC		= CtattrProtoinfoTcp.CTA_PROTOINFO_TCP_UNSPEC
CTA_PROTOINFO_TCP_STATE			= CtattrProtoinfoTcp.CTA_PROTOINFO_TCP_STATE
CTA_PROTOINFO_TCP_WSCALE_ORIGINAL	= CtattrProtoinfoTcp.CTA_PROTOINFO_TCP_WSCALE_ORIGINAL
CTA_PROTOINFO_TCP_WSCALE_REPLY		= CtattrProtoinfoTcp.CTA_PROTOINFO_TCP_WSCALE_REPLY
CTA_PROTOINFO_TCP_FLAGS_ORIGINAL	= CtattrProtoinfoTcp.CTA_PROTOINFO_TCP_FLAGS_ORIGINAL
CTA_PROTOINFO_TCP_FLAGS_REPLY		= CtattrProtoinfoTcp.CTA_PROTOINFO_TCP_FLAGS_REPLY
CTA_PROTOINFO_TCP_MAX			= CtattrProtoinfoTcp.CTA_PROTOINFO_TCP_MAX

# enum ctattr_protoinfo_dccp
class CtattrProtoinfoDccp(object):
    CTA_PROTOINFO_DCCP_UNSPEC		= 0
    CTA_PROTOINFO_DCCP_STATE		= 1
    CTA_PROTOINFO_DCCP_ROLE		= 2
    CTA_PROTOINFO_DCCP_HANDSHAKE_SEQ	= 3
    CTA_PROTOINFO_DCCP_PAD		= 4
    __CTA_PROTOINFO_DCCP_MAX		= 5
    CTA_PROTOINFO_DCCP_MAX		= (__CTA_PROTOINFO_DCCP_MAX - 1)
CTA_PROTOINFO_DCCP_UNSPEC		= CtattrProtoinfoDccp.CTA_PROTOINFO_DCCP_UNSPEC
CTA_PROTOINFO_DCCP_STATE		= CtattrProtoinfoDccp.CTA_PROTOINFO_DCCP_STATE
CTA_PROTOINFO_DCCP_ROLE			= CtattrProtoinfoDccp.CTA_PROTOINFO_DCCP_ROLE
CTA_PROTOINFO_DCCP_HANDSHAKE_SEQ	= CtattrProtoinfoDccp.CTA_PROTOINFO_DCCP_HANDSHAKE_SEQ
CTA_PROTOINFO_DCCP_PAD			= CtattrProtoinfoDccp.CTA_PROTOINFO_DCCP_PAD
CTA_PROTOINFO_DCCP_MAX			= CtattrProtoinfoDccp.CTA_PROTOINFO_DCCP_MAX

# enum ctattr_protoinfo_sctp
class CtattrProtoinfoSctp(object):
    CTA_PROTOINFO_SCTP_UNSPEC		= 0
    CTA_PROTOINFO_SCTP_STATE		= 1
    CTA_PROTOINFO_SCTP_VTAG_ORIGINAL	= 2
    CTA_PROTOINFO_SCTP_VTAG_REPLY	= 3
    __CTA_PROTOINFO_SCTP_MAX		= 4
    CTA_PROTOINFO_SCTP_MAX		= (__CTA_PROTOINFO_SCTP_MAX - 1)
CTA_PROTOINFO_SCTP_UNSPEC		= CtattrProtoinfoSctp.CTA_PROTOINFO_SCTP_UNSPEC
CTA_PROTOINFO_SCTP_STATE		= CtattrProtoinfoSctp.CTA_PROTOINFO_SCTP_STATE
CTA_PROTOINFO_SCTP_VTAG_ORIGINAL	= CtattrProtoinfoSctp.CTA_PROTOINFO_SCTP_VTAG_ORIGINAL
CTA_PROTOINFO_SCTP_VTAG_REPLY		= CtattrProtoinfoSctp.CTA_PROTOINFO_SCTP_VTAG_REPLY
CTA_PROTOINFO_SCTP_MAX			= CtattrProtoinfoSctp.CTA_PROTOINFO_SCTP_MAX

# enum ctattr_counters
class CtattrCounters(object):
    CTA_COUNTERS_UNSPEC		= 0
    CTA_COUNTERS_PACKETS	= 1
    CTA_COUNTERS_BYTES		= 2
    CTA_COUNTERS32_PACKETS	= 3
    CTA_COUNTERS32_BYTES	= 4
    CTA_COUNTERS_PAD		= 5
    __CTA_COUNTERS_MAX		= 6
    CTA_COUNTERS_MAX		= (__CTA_COUNTERS_MAX - 1)
CTA_COUNTERS_UNSPEC	= CtattrCounters.CTA_COUNTERS_UNSPEC
CTA_COUNTERS_PACKETS	= CtattrCounters.CTA_COUNTERS_PACKETS
CTA_COUNTERS_BYTES	= CtattrCounters.CTA_COUNTERS_BYTES
CTA_COUNTERS32_PACKETS	= CtattrCounters.CTA_COUNTERS32_PACKETS
CTA_COUNTERS32_BYTES	= CtattrCounters.CTA_COUNTERS32_BYTES
CTA_COUNTERS_PAD	= CtattrCounters.CTA_COUNTERS_PAD
CTA_COUNTERS_MAX	= CtattrCounters.CTA_COUNTERS_MAX

# enum ctattr_tstamp
class CtattrTstamp(object):
    CTA_TIMESTAMP_UNSPEC	= 0
    CTA_TIMESTAMP_START		= 1
    CTA_TIMESTAMP_STOP		= 2
    CTA_TIMESTAMP_PAD		= 3
    __CTA_TIMESTAMP_MAX		= 4
    CTA_TIMESTAMP_MAX		= (__CTA_TIMESTAMP_MAX - 1)
CTA_TIMESTAMP_UNSPEC	= CtattrTstamp.CTA_TIMESTAMP_UNSPEC
CTA_TIMESTAMP_START	= CtattrTstamp.CTA_TIMESTAMP_START
CTA_TIMESTAMP_STOP	= CtattrTstamp.CTA_TIMESTAMP_STOP
CTA_TIMESTAMP_PAD	= CtattrTstamp.CTA_TIMESTAMP_PAD
CTA_TIMESTAMP_MAX	= CtattrTstamp.CTA_TIMESTAMP_MAX

# enum ctattr_nat
class CtattrNat(object):
    CTA_NAT_UNSPEC	= 0
    CTA_NAT_V4_MINIP	= 1
    CTA_NAT_MINIP	= CTA_NAT_V4_MINIP
    CTA_NAT_V4_MAXIP	= 2
    CTA_NAT_MAXIP	= CTA_NAT_V4_MAXIP
    CTA_NAT_PROTO	= 3
    CTA_NAT_V6_MINIP	= 4
    CTA_NAT_V6_MAXIP	= 5
    __CTA_NAT_MAX	= 6
    CTA_NAT_MAX		= (__CTA_NAT_MAX - 1)
CTA_NAT_UNSPEC		= CtattrNat.CTA_NAT_UNSPEC
CTA_NAT_V4_MINIP	= CtattrNat.CTA_NAT_V4_MINIP
CTA_NAT_MINIP		= CtattrNat.CTA_NAT_MINIP
CTA_NAT_V4_MAXIP	= CtattrNat.CTA_NAT_V4_MAXIP
CTA_NAT_MAXIP		= CtattrNat.CTA_NAT_MAXIP
CTA_NAT_PROTO		= CtattrNat.CTA_NAT_PROTO
CTA_NAT_V6_MINIP	= CtattrNat.CTA_NAT_V6_MINIP
CTA_NAT_V6_MAXIP	= CtattrNat.CTA_NAT_V6_MAXIP
CTA_NAT_MAX		= CtattrNat.CTA_NAT_MAX

# enum ctattr_protonat
class CtattrProtonat(object):
    CTA_PROTONAT_UNSPEC		= 0
    CTA_PROTONAT_PORT_MIN	= 1
    CTA_PROTONAT_PORT_MAX	= 2
    __CTA_PROTONAT_MAX		= 3
    CTA_PROTONAT_MAX		= (__CTA_PROTONAT_MAX - 1)
CTA_PROTONAT_UNSPEC	= CtattrProtonat.CTA_PROTONAT_UNSPEC
CTA_PROTONAT_PORT_MIN	= CtattrProtonat.CTA_PROTONAT_PORT_MIN
CTA_PROTONAT_PORT_MAX	= CtattrProtonat.CTA_PROTONAT_PORT_MAX
CTA_PROTONAT_MAX	= CtattrProtonat.CTA_PROTONAT_MAX

# enum ctattr_seqadj
class CtattrSeqadj(object):
    CTA_SEQADJ_UNSPEC		= 0
    CTA_SEQADJ_CORRECTION_POS	= 1
    CTA_SEQADJ_OFFSET_BEFORE	= 2
    CTA_SEQADJ_OFFSET_AFTER	= 3
    __CTA_SEQADJ_MAX		= 4
    CTA_SEQADJ_MAX		= (__CTA_SEQADJ_MAX - 1)
CTA_SEQADJ_UNSPEC		= CtattrSeqadj.CTA_SEQADJ_UNSPEC
CTA_SEQADJ_CORRECTION_POS	= CtattrSeqadj.CTA_SEQADJ_CORRECTION_POS
CTA_SEQADJ_OFFSET_BEFORE	= CtattrSeqadj.CTA_SEQADJ_OFFSET_BEFORE
CTA_SEQADJ_OFFSET_AFTER		= CtattrSeqadj.CTA_SEQADJ_OFFSET_AFTER
CTA_SEQADJ_MAX			= CtattrSeqadj.CTA_SEQADJ_MAX

# enum ctattr_natseq
class CtattrNatseq(object):
    CTA_NAT_SEQ_UNSPEC		= 0
    CTA_NAT_SEQ_CORRECTION_POS	= 1
    CTA_NAT_SEQ_OFFSET_BEFORE	= 2
    CTA_NAT_SEQ_OFFSET_AFTER	= 3
    __CTA_NAT_SEQ_MAX		= 4
    CTA_NAT_SEQ_MAX		= (__CTA_NAT_SEQ_MAX - 1)
CTA_NAT_SEQ_UNSPEC		= CtattrNatseq.CTA_NAT_SEQ_UNSPEC
CTA_NAT_SEQ_CORRECTION_POS	= CtattrNatseq.CTA_NAT_SEQ_CORRECTION_POS
CTA_NAT_SEQ_OFFSET_BEFORE	= CtattrNatseq.CTA_NAT_SEQ_OFFSET_BEFORE
CTA_NAT_SEQ_OFFSET_AFTER	= CtattrNatseq.CTA_NAT_SEQ_OFFSET_AFTER
CTA_NAT_SEQ_MAX			= CtattrNatseq.CTA_NAT_SEQ_MAX

# enum ctattr_expect
class CtattrExpect(object):
    CTA_EXPECT_UNSPEC		= 0
    CTA_EXPECT_MASTER		= 1
    CTA_EXPECT_TUPLE		= 2
    CTA_EXPECT_MASK		= 3
    CTA_EXPECT_TIMEOUT		= 4
    CTA_EXPECT_ID		= 5
    CTA_EXPECT_HELP_NAME	= 6
    CTA_EXPECT_ZONE		= 7
    CTA_EXPECT_FLAGS		= 8
    CTA_EXPECT_CLASS		= 9
    CTA_EXPECT_NAT		= 10
    CTA_EXPECT_FN		= 11
    __CTA_EXPECT_MAX		= 12
    CTA_EXPECT_MAX		= (__CTA_EXPECT_MAX - 1)
CTA_EXPECT_UNSPEC	= CtattrExpect.CTA_EXPECT_UNSPEC
CTA_EXPECT_MASTER	= CtattrExpect.CTA_EXPECT_MASTER
CTA_EXPECT_TUPLE	= CtattrExpect.CTA_EXPECT_TUPLE
CTA_EXPECT_MASK		= CtattrExpect.CTA_EXPECT_MASK
CTA_EXPECT_TIMEOUT	= CtattrExpect.CTA_EXPECT_TIMEOUT
CTA_EXPECT_ID		= CtattrExpect.CTA_EXPECT_ID
CTA_EXPECT_HELP_NAME	= CtattrExpect.CTA_EXPECT_HELP_NAME
CTA_EXPECT_ZONE		= CtattrExpect.CTA_EXPECT_ZONE
CTA_EXPECT_FLAGS	= CtattrExpect.CTA_EXPECT_FLAGS
CTA_EXPECT_CLASS	= CtattrExpect.CTA_EXPECT_CLASS
CTA_EXPECT_NAT		= CtattrExpect.CTA_EXPECT_NAT
CTA_EXPECT_FN		= CtattrExpect.CTA_EXPECT_FN
CTA_EXPECT_MAX		= CtattrExpect.CTA_EXPECT_MAX

# enum ctattr_expect_nat
class CtattrExpectNat(object):
    CTA_EXPECT_NAT_UNSPEC	= 0
    CTA_EXPECT_NAT_DIR		= 1
    CTA_EXPECT_NAT_TUPLE	= 2
    __CTA_EXPECT_NAT_MAX	= 3
    CTA_EXPECT_NAT_MAX		= (__CTA_EXPECT_NAT_MAX - 1)
CTA_EXPECT_NAT_UNSPEC	= CtattrExpectNat.CTA_EXPECT_NAT_UNSPEC
CTA_EXPECT_NAT_DIR	= CtattrExpectNat.CTA_EXPECT_NAT_DIR
CTA_EXPECT_NAT_TUPLE	= CtattrExpectNat.CTA_EXPECT_NAT_TUPLE
CTA_EXPECT_NAT_MAX	= CtattrExpectNat.CTA_EXPECT_NAT_MAX

# enum ctattr_help
class CtattrHelp(object):
    CTA_HELP_UNSPEC	= 0
    CTA_HELP_NAME	= 1
    CTA_HELP_INFO	= 2
    __CTA_HELP_MAX	= 3
    CTA_HELP_MAX	= (__CTA_HELP_MAX - 1)
CTA_HELP_UNSPEC	= CtattrHelp.CTA_HELP_UNSPEC
CTA_HELP_NAME	= CtattrHelp.CTA_HELP_NAME
CTA_HELP_INFO	= CtattrHelp.CTA_HELP_INFO
CTA_HELP_MAX	= CtattrHelp.CTA_HELP_MAX

# enum ctattr_secctx
class CtattrSecctx(object):
    CTA_SECCTX_UNSPEC	= 0
    CTA_SECCTX_NAME	= 1
    __CTA_SECCTX_MAX	= 2
    CTA_SECCTX_MAX	= (__CTA_SECCTX_MAX - 1)
CTA_SECCTX_UNSPEC	= CtattrSecctx.CTA_SECCTX_UNSPEC
CTA_SECCTX_NAME		= CtattrSecctx.CTA_SECCTX_NAME
CTA_SECCTX_MAX		= CtattrSecctx.CTA_SECCTX_MAX

# enum ctattr_stats_cpu
class CtattrStatsCpu(object):
    CTA_STATS_UNSPEC		= 0
    CTA_STATS_SEARCHED		= 1  # no longer used
    CTA_STATS_FOUND		= 2
    CTA_STATS_NEW		= 3  # no longer used
    CTA_STATS_INVALID		= 4
    CTA_STATS_IGNORE		= 5
    CTA_STATS_DELETE		= 6  # no longer used
    CTA_STATS_DELETE_LIST	= 7  # no longer used
    CTA_STATS_INSERT		= 8
    CTA_STATS_INSERT_FAILED	= 9
    CTA_STATS_DROP		= 10
    CTA_STATS_EARLY_DROP	= 11
    CTA_STATS_ERROR		= 12
    CTA_STATS_SEARCH_RESTART	= 13
    __CTA_STATS_MAX		= 14
    CTA_STATS_MAX		= (__CTA_STATS_MAX - 1)
CTA_STATS_UNSPEC		= CtattrStatsCpu.CTA_STATS_UNSPEC
CTA_STATS_SEARCHED		= CtattrStatsCpu.CTA_STATS_SEARCHED
CTA_STATS_FOUND			= CtattrStatsCpu.CTA_STATS_FOUND
CTA_STATS_NEW			= CtattrStatsCpu.CTA_STATS_NEW
CTA_STATS_INVALID		= CtattrStatsCpu.CTA_STATS_INVALID
CTA_STATS_IGNORE		= CtattrStatsCpu.CTA_STATS_IGNORE
CTA_STATS_DELETE		= CtattrStatsCpu.CTA_STATS_DELETE
CTA_STATS_DELETE_LIST		= CtattrStatsCpu.CTA_STATS_DELETE_LIST
CTA_STATS_INSERT		= CtattrStatsCpu.CTA_STATS_INSERT
CTA_STATS_INSERT_FAILED		= CtattrStatsCpu.CTA_STATS_INSERT_FAILED
CTA_STATS_DROP			= CtattrStatsCpu.CTA_STATS_DROP
CTA_STATS_EARLY_DROP		= CtattrStatsCpu.CTA_STATS_EARLY_DROP
CTA_STATS_ERROR			= CtattrStatsCpu.CTA_STATS_ERROR
CTA_STATS_SEARCH_RESTART	= CtattrStatsCpu.CTA_STATS_SEARCH_RESTART
CTA_STATS_MAX			= CtattrStatsCpu.CTA_STATS_MAX

# enum ctattr_stats_global
class CtattrStatsGlobal(object):
    CTA_STATS_GLOBAL_UNSPEC	= 0
    CTA_STATS_GLOBAL_ENTRIES	= 1
    __CTA_STATS_GLOBAL_MAX	= 2
    CTA_STATS_GLOBAL_MAX	= (__CTA_STATS_GLOBAL_MAX - 1)
CTA_STATS_GLOBAL_UNSPEC		= CtattrStatsGlobal.CTA_STATS_GLOBAL_UNSPEC
CTA_STATS_GLOBAL_ENTRIES	= CtattrStatsGlobal.CTA_STATS_GLOBAL_ENTRIES
CTA_STATS_GLOBAL_MAX		= CtattrStatsGlobal.CTA_STATS_GLOBAL_MAX

# enum ctattr_expect_stats
class CtattrExpectStats(object):
    CTA_STATS_EXP_UNSPEC	= 0
    CTA_STATS_EXP_NEW		= 1
    CTA_STATS_EXP_CREATE	= 2
    CTA_STATS_EXP_DELETE	= 3
    __CTA_STATS_EXP_MAX		= 4
    CTA_STATS_EXP_MAX		= (__CTA_STATS_EXP_MAX - 1)
CTA_STATS_EXP_UNSPEC	= CtattrExpectStats.CTA_STATS_EXP_UNSPEC
CTA_STATS_EXP_NEW	= CtattrExpectStats.CTA_STATS_EXP_NEW
CTA_STATS_EXP_CREATE	= CtattrExpectStats.CTA_STATS_EXP_CREATE
CTA_STATS_EXP_DELETE	= CtattrExpectStats.CTA_STATS_EXP_DELETE
CTA_STATS_EXP_MAX	= CtattrExpectStats.CTA_STATS_EXP_MAX
