# -*- coding: utf-8 -*-

try:
    from enum import Enum
except ImportError:
    Enum = object


# enum cntl_msg_types
class CtnlMsgTypes(Enum):
    IPCTNL_MSG_CT_NEW			= 0
    IPCTNL_MSG_CT_GET			= 1
    IPCTNL_MSG_CT_DELETE		= 2
    IPCTNL_MSG_CT_GET_CTRZERO		= 3
    IPCTNL_MSG_CT_GET_STATS_CPU		= 4
    IPCTNL_MSG_CT_GET_STATS		= 5
    IPCTNL_MSG_CT_GET_DYING		= 6
    IPCTNL_MSG_CT_GET_UNCONFIRMED	= 7
    IPCTNL_MSG_MAX			= 8
IPCTNL_MSG_CT_NEW		= 0
IPCTNL_MSG_CT_GET		= 1
IPCTNL_MSG_CT_DELETE		= 2
IPCTNL_MSG_CT_GET_CTRZERO	= 3
IPCTNL_MSG_CT_GET_STATS_CPU	= 4
IPCTNL_MSG_CT_GET_STATS		= 5
IPCTNL_MSG_CT_GET_DYING		= 6
IPCTNL_MSG_CT_GET_UNCONFIRMED	= 7
IPCTNL_MSG_MAX			= 8

# enum ctnl_exp_msg_types
class CtnlExpMsgTypes(Enum):
    IPCTNL_MSG_EXP_NEW			= 0
    IPCTNL_MSG_EXP_GET			= 1
    IPCTNL_MSG_EXP_DELETE		= 2
    IPCTNL_MSG_EXP_GET_STATS_CPU	= 3
    IPCTNL_MSG_EXP_MAX			= 4
IPCTNL_MSG_EXP_NEW		= 0
IPCTNL_MSG_EXP_GET		= 1
IPCTNL_MSG_EXP_DELETE		= 2
IPCTNL_MSG_EXP_GET_STATS_CPU	= 3
IPCTNL_MSG_EXP_MAX		= 4

# enum ctattr_type
class CtattrType(Enum):
    CTA_UNSPEC			= 0
    CTA_TUPLE_ORIG		= 1
    CTA_TUPLE_REPLY		= 2
    CTA_STATUS			= 3
    CTA_PROTOINFO		= 4
    CTA_HELP			= 5
    CTA_NAT_SRC			= 6
    CTA_NAT			= CTA_NAT_SRC # backwards compatibility
    CTA_TIMEOUT			= 7
    CTA_MARK			= 8
    CTA_COUNTERS_ORIG		= 9
    CTA_COUNTERS_REPLY		= 10
    CTA_USE			= 11
    CTA_ID			= 12
    CTA_NAT_DST			= 13
    CTA_TUPLE_MASTER		= 14
    CTA_SEQ_ADJ_ORIG		= 15
    CTA_NAT_SEQ_ADJ_ORIG	= CTA_SEQ_ADJ_ORIG
    CTA_SEQ_ADJ_REPLY		= 16
    CTA_NAT_SEQ_ADJ_REPLY	= CTA_SEQ_ADJ_REPLY
    CTA_SECMARK			= 17 # obsolete
    CTA_ZONE			= 18
    CTA_SECCTX			= 19
    CTA_TIMESTAMP		= 20
    CTA_MARK_MASK		= 21
    CTA_LABELS			= 22
    CTA_LABELS_MASK		= 23
    __CTA_MAX			= 24
    CTA_MAX			= (__CTA_MAX - 1)
CTA_UNSPEC		= CtattrType.CTA_UNSPEC
CTA_TUPLE_ORIG		= CtattrType.CTA_TUPLE_ORIG
CTA_TUPLE_REPLY		= CtattrType.CTA_TUPLE_REPLY
CTA_STATUS		= CtattrType.CTA_STATUS
CTA_PROTOINFO		= CtattrType.CTA_PROTOINFO
CTA_HELP		= CtattrType.CTA_HELP
CTA_NAT_SRC		= CtattrType.CTA_NAT_SRC
CTA_NAT			= CtattrType.CTA_NAT
CTA_TIMEOUT		= CtattrType.CTA_TIMEOUT
CTA_MARK		= CtattrType.CTA_MARK
CTA_COUNTERS_ORIG	= CtattrType.CTA_COUNTERS_ORIG
CTA_COUNTERS_REPLY	= CtattrType.CTA_COUNTERS_REPLY
CTA_USE			= CtattrType.CTA_USE
CTA_ID			= CtattrType.CTA_ID
CTA_NAT_DST		= CtattrType.CTA_NAT_DST
CTA_TUPLE_MASTER	= CtattrType.CTA_TUPLE_MASTER
CTA_SEQ_ADJ_ORIG	= CtattrType.CTA_SEQ_ADJ_ORIG
CTA_NAT_SEQ_ADJ_ORIG	= CtattrType.CTA_NAT_SEQ_ADJ_ORIG
CTA_SEQ_ADJ_REPLY	= CtattrType.CTA_SEQ_ADJ_REPLY
CTA_NAT_SEQ_ADJ_REPLY	= CtattrType.CTA_NAT_SEQ_ADJ_REPLY
CTA_SECMARK		= CtattrType.CTA_SECMARK
CTA_ZONE		= CtattrType.CTA_ZONE
CTA_SECCTX		= CtattrType.CTA_SECCTX
CTA_TIMESTAMP		= CtattrType.CTA_TIMESTAMP
CTA_MARK_MASK		= CtattrType.CTA_MARK_MASK
CTA_LABELS		= CtattrType.CTA_LABELS
CTA_LABELS_MASK		= CtattrType.CTA_LABELS_MASK
CTA_MAX			= CtattrType.CTA_MAX

# enum ctattr_tuple
class CtattrTuple(Enum):
    CTA_TUPLE_UNSPEC	= 0
    CTA_TUPLE_IP	= 1
    CTA_TUPLE_PROTO	= 2
    __CTA_TUPLE_MAX	= 3
    CTA_TUPLE_MAX	= (__CTA_TUPLE_MAX - 1)
CTA_TUPLE_UNSPEC	= 0
CTA_TUPLE_IP		= 1
CTA_TUPLE_PROTO		= 2
__CTA_TUPLE_MAX		= 3
CTA_TUPLE_MAX		= (__CTA_TUPLE_MAX - 1)

# enum ctattr_ip
class CtattrIp(Enum):
    CTA_IP_UNSPEC	= 0
    CTA_IP_V4_SRC	= 1
    CTA_IP_V4_DST	= 2
    CTA_IP_V6_SRC	= 3
    CTA_IP_V6_DST	= 4
    __CTA_IP_MAX	= 5
    CTA_IP_MAX		= (__CTA_IP_MAX - 1)
CTA_IP_UNSPEC	= 0
CTA_IP_V4_SRC	= 1
CTA_IP_V4_DST	= 2
CTA_IP_V6_SRC	= 3
CTA_IP_V6_DST	= 4
__CTA_IP_MAX	= 5
CTA_IP_MAX	= (__CTA_IP_MAX - 1)

# enum ctattr_l4proto
class CtattrL4proto(Enum):
    CTA_PROTO_UNSPEC		= 0
    CTA_PROTO_NUM		= 1
    CTA_PROTO_SRC_PORT		= 2
    CTA_PROTO_DST_PORT		= 3
    CTA_PROTO_ICMP_ID		= 4
    CTA_PROTO_ICMP_TYPE		= 5
    CTA_PROTO_ICMP_CODE		= 6
    CTA_PROTO_ICMPV6_ID		= 7
    CTA_PROTO_ICMPV6_TYPE	= 8
    CTA_PROTO_ICMPV6_CODE	= 9
    __CTA_PROTO_MAX		= 10
    CTA_PROTO_MAX		= (__CTA_PROTO_MAX - 1)
CTA_PROTO_UNSPEC	= 0
CTA_PROTO_NUM		= 1
CTA_PROTO_SRC_PORT	= 2
CTA_PROTO_DST_PORT	= 3
CTA_PROTO_ICMP_ID	= 4
CTA_PROTO_ICMP_TYPE	= 5
CTA_PROTO_ICMP_CODE	= 6
CTA_PROTO_ICMPV6_ID	= 7
CTA_PROTO_ICMPV6_TYPE	= 8
CTA_PROTO_ICMPV6_CODE	= 9
__CTA_PROTO_MAX		= 10
CTA_PROTO_MAX		= (__CTA_PROTO_MAX - 1)

# enum ctattr_protoinfo
class CtattrProtoinfo(Enum):
    CTA_PROTOINFO_UNSPEC	= 0
    CTA_PROTOINFO_TCP		= 1
    CTA_PROTOINFO_DCCP		= 2
    CTA_PROTOINFO_SCTP		= 3
    __CTA_PROTOINFO_MAX		= 4
    CTA_PROTOINFO_MAX		= (__CTA_PROTOINFO_MAX - 1)
CTA_PROTOINFO_UNSPEC	= 0
CTA_PROTOINFO_TCP	= 1
CTA_PROTOINFO_DCCP	= 2
CTA_PROTOINFO_SCTP	= 3
__CTA_PROTOINFO_MAX	= 4
CTA_PROTOINFO_MAX	= (__CTA_PROTOINFO_MAX - 1)

# enum ctattr_protoinfo_tcp
class CtattrProtoinfoTcp(Enum):
    CTA_PROTOINFO_TCP_UNSPEC		= 0
    CTA_PROTOINFO_TCP_STATE		= 1
    CTA_PROTOINFO_TCP_WSCALE_ORIGINAL	= 2
    CTA_PROTOINFO_TCP_WSCALE_REPLY	= 3
    CTA_PROTOINFO_TCP_FLAGS_ORIGINAL	= 4
    CTA_PROTOINFO_TCP_FLAGS_REPLY	= 5
    __CTA_PROTOINFO_TCP_MAX		= 6
    CTA_PROTOINFO_TCP_MAX		= (__CTA_PROTOINFO_TCP_MAX - 1)
CTA_PROTOINFO_TCP_UNSPEC		= 0
CTA_PROTOINFO_TCP_STATE			= 1
CTA_PROTOINFO_TCP_WSCALE_ORIGINAL	= 2
CTA_PROTOINFO_TCP_WSCALE_REPLY		= 3
CTA_PROTOINFO_TCP_FLAGS_ORIGINAL	= 4
CTA_PROTOINFO_TCP_FLAGS_REPLY		= 5
__CTA_PROTOINFO_TCP_MAX			= 6
CTA_PROTOINFO_TCP_MAX			= (__CTA_PROTOINFO_TCP_MAX - 1)

# enum ctattr_protoinfo_dccp
class CtattrProtoinfoDccp(Enum):
    CTA_PROTOINFO_DCCP_UNSPEC		= 0
    CTA_PROTOINFO_DCCP_STATE		= 1
    CTA_PROTOINFO_DCCP_ROLE		= 2
    CTA_PROTOINFO_DCCP_HANDSHAKE_SEQ	= 3
    __CTA_PROTOINFO_DCCP_MAX		= 4
    CTA_PROTOINFO_DCCP_MAX		= (__CTA_PROTOINFO_DCCP_MAX - 1)
CTA_PROTOINFO_DCCP_UNSPEC		= 0
CTA_PROTOINFO_DCCP_STATE		= 1
CTA_PROTOINFO_DCCP_ROLE			= 2
CTA_PROTOINFO_DCCP_HANDSHAKE_SEQ	= 3
__CTA_PROTOINFO_DCCP_MAX		= 4
CTA_PROTOINFO_DCCP_MAX			= (__CTA_PROTOINFO_DCCP_MAX - 1)

# enum ctattr_protoinfo_sctp
class CtattrProtoinfoSctp(Enum):
    CTA_PROTOINFO_SCTP_UNSPEC		= 0
    CTA_PROTOINFO_SCTP_STATE		= 1
    CTA_PROTOINFO_SCTP_VTAG_ORIGINAL	= 2
    CTA_PROTOINFO_SCTP_VTAG_REPLY	= 3
    __CTA_PROTOINFO_SCTP_MAX		= 4
    CTA_PROTOINFO_SCTP_MAX		= (__CTA_PROTOINFO_SCTP_MAX - 1)
CTA_PROTOINFO_SCTP_UNSPEC		= 0
CTA_PROTOINFO_SCTP_STATE		= 1
CTA_PROTOINFO_SCTP_VTAG_ORIGINAL	= 2
CTA_PROTOINFO_SCTP_VTAG_REPLY		= 3
__CTA_PROTOINFO_SCTP_MAX		= 4
CTA_PROTOINFO_SCTP_MAX			= (__CTA_PROTOINFO_SCTP_MAX - 1)

# enum ctattr_counters
class CtattrCounters(Enum):
    CTA_COUNTERS_UNSPEC		= 0
    CTA_COUNTERS_PACKETS	= 1
    CTA_COUNTERS_BYTES		= 2
    CTA_COUNTERS32_PACKETS	= 3
    CTA_COUNTERS32_BYTES	= 4
    __CTA_COUNTERS_MAX		= 5
    CTA_COUNTERS_MAX		= (__CTA_COUNTERS_MAX - 1)
CTA_COUNTERS_UNSPEC	= 0
CTA_COUNTERS_PACKETS	= 1
CTA_COUNTERS_BYTES	= 2
CTA_COUNTERS32_PACKETS	= 3
CTA_COUNTERS32_BYTES	= 4
__CTA_COUNTERS_MAX	= 5
CTA_COUNTERS_MAX	= (__CTA_COUNTERS_MAX - 1)

# enum ctattr_tstamp
class CtattrTstamp(Enum):
    CTA_TIMESTAMP_UNSPEC	= 0
    CTA_TIMESTAMP_START		= 1
    CTA_TIMESTAMP_STOP		= 2
    __CTA_TIMESTAMP_MAX		= 3
    CTA_TIMESTAMP_MAX		= (__CTA_TIMESTAMP_MAX - 1)
CTA_TIMESTAMP_UNSPEC	= 0
CTA_TIMESTAMP_START	= 1
CTA_TIMESTAMP_STOP	= 2
__CTA_TIMESTAMP_MAX	= 3
CTA_TIMESTAMP_MAX	= (__CTA_TIMESTAMP_MAX - 1)

# enum ctattr_nat
class CtattrNat(Enum):
    CTA_NAT_UNSPEC	= 0
    CTA_NAT_V4_MINIP	= 1
    CTA_NAT_MINIP	= CTA_NAT_V4_MINIP
    CTA_NAT_V4_MAXIP	= 2
    CTA_NAT_MAXIP	= CTA_NAT_V4_MAXIP
    CTA_NAT_PROTO	= 3
    CTA_NAT_V6_MINIP	= 4
    CTA_NAT_V6_MAXIP	= 5
    __CTA_NAT_MAX	= 6
    CTA_NAT_MAX		= (__CTA_NAT_MAX - 1)
CTA_NAT_UNSPEC		= 0
CTA_NAT_V4_MINIP	= 1
CTA_NAT_MINIP		= CTA_NAT_V4_MINIP
CTA_NAT_V4_MAXIP	= 2
CTA_NAT_MAXIP		= CTA_NAT_V4_MAXIP
CTA_NAT_PROTO		= 3
CTA_NAT_V6_MINIP	= 4
CTA_NAT_V6_MAXIP	= 5
__CTA_NAT_MAX		= 6
CTA_NAT_MAX		= (__CTA_NAT_MAX - 1)

# enum ctattr_protonat
class CtattrProtonat(Enum):
    CTA_PROTONAT_UNSPEC		= 0
    CTA_PROTONAT_PORT_MIN	= 1
    CTA_PROTONAT_PORT_MAX	= 2
    __CTA_PROTONAT_MAX		= 3
    CTA_PROTONAT_MAX		= (__CTA_PROTONAT_MAX - 1)
CTA_PROTONAT_UNSPEC	= 0
CTA_PROTONAT_PORT_MIN	= 1
CTA_PROTONAT_PORT_MAX	= 2
__CTA_PROTONAT_MAX	= 3
CTA_PROTONAT_MAX	= (__CTA_PROTONAT_MAX - 1)

# enum ctattr_seqadj
class CtattrSeqadj(Enum):
    CTA_SEQADJ_UNSPEC		= 0
    CTA_SEQADJ_CORRECTION_POS	= 1
    CTA_SEQADJ_OFFSET_BEFORE	= 2
    CTA_SEQADJ_OFFSET_AFTER	= 3
    __CTA_SEQADJ_MAX		= 4
    CTA_SEQADJ_MAX		= (__CTA_SEQADJ_MAX - 1)
CTA_SEQADJ_UNSPEC		= 0
CTA_SEQADJ_CORRECTION_POS	= 1
CTA_SEQADJ_OFFSET_BEFORE	= 2
CTA_SEQADJ_OFFSET_AFTER		= 3
__CTA_SEQADJ_MAX		= 4
CTA_SEQADJ_MAX			= (__CTA_SEQADJ_MAX - 1)

# enum ctattr_natseq
class CtattrNatseq(Enum):
    CTA_NAT_SEQ_UNSPEC		= 0
    CTA_NAT_SEQ_CORRECTION_POS	= 1
    CTA_NAT_SEQ_OFFSET_BEFORE	= 2
    CTA_NAT_SEQ_OFFSET_AFTER	= 3
    __CTA_NAT_SEQ_MAX		= 4
    CTA_NAT_SEQ_MAX		= (__CTA_NAT_SEQ_MAX - 1)
CTA_NAT_SEQ_UNSPEC		= 0
CTA_NAT_SEQ_CORRECTION_POS	= 1
CTA_NAT_SEQ_OFFSET_BEFORE	= 2
CTA_NAT_SEQ_OFFSET_AFTER	= 3
__CTA_NAT_SEQ_MAX		= 4
CTA_NAT_SEQ_MAX			= (__CTA_NAT_SEQ_MAX - 1)

# enum ctattr_expect
class CtattrExpect(Enum):
    CTA_EXPECT_UNSPEC		= 0
    CTA_EXPECT_MASTER		= 1
    CTA_EXPECT_TUPLE		= 2
    CTA_EXPECT_MASK		= 3
    CTA_EXPECT_TIMEOUT		= 4
    CTA_EXPECT_ID		= 5
    CTA_EXPECT_HELP_NAME	= 6
    CTA_EXPECT_ZONE		= 7
    CTA_EXPECT_FLAGS		= 8
    CTA_EXPECT_CLASS		= 9
    CTA_EXPECT_NAT		= 10
    CTA_EXPECT_FN		= 11
    __CTA_EXPECT_MAX		= 12
    CTA_EXPECT_MAX		= (__CTA_EXPECT_MAX - 1)
CTA_EXPECT_UNSPEC	= 0
CTA_EXPECT_MASTER	= 1
CTA_EXPECT_TUPLE	= 2
CTA_EXPECT_MASK		= 3
CTA_EXPECT_TIMEOUT	= 4
CTA_EXPECT_ID		= 5
CTA_EXPECT_HELP_NAME	= 6
CTA_EXPECT_ZONE		= 7
CTA_EXPECT_FLAGS	= 8
CTA_EXPECT_CLASS	= 9
CTA_EXPECT_NAT		= 10
CTA_EXPECT_FN		= 11
__CTA_EXPECT_MAX	= 12
CTA_EXPECT_MAX		= (__CTA_EXPECT_MAX - 1)

# enum ctattr_expect_nat
class CtattrExpectNat(Enum):
    CTA_EXPECT_NAT_UNSPEC	= 0
    CTA_EXPECT_NAT_DIR		= 1
    CTA_EXPECT_NAT_TUPLE	= 2
    __CTA_EXPECT_NAT_MAX	= 3
    CTA_EXPECT_NAT_MAX		= (__CTA_EXPECT_NAT_MAX - 1)
CTA_EXPECT_NAT_UNSPEC	= 0
CTA_EXPECT_NAT_DIR	= 1
CTA_EXPECT_NAT_TUPLE	= 2
__CTA_EXPECT_NAT_MAX	= 3
CTA_EXPECT_NAT_MAX	= (__CTA_EXPECT_NAT_MAX - 1)

# enum ctattr_help
class CtattrHelp(Enum):
    CTA_HELP_UNSPEC	= 0
    CTA_HELP_NAME	= 1
    CTA_HELP_INFO	= 2
    __CTA_HELP_MAX	= 3
    CTA_HELP_MAX	= (__CTA_HELP_MAX - 1)
CTA_HELP_UNSPEC	= 0
CTA_HELP_NAME	= 1
CTA_HELP_INFO	= 2
__CTA_HELP_MAX	= 3
CTA_HELP_MAX	= (__CTA_HELP_MAX - 1)

# enum ctattr_secctx
class CtattrSecctx(Enum):
    CTA_SECCTX_UNSPEC	= 0
    CTA_SECCTX_NAME	= 1
    __CTA_SECCTX_MAX	= 2
    CTA_SECCTX_MAX	= (__CTA_SECCTX_MAX - 1)
CTA_SECCTX_UNSPEC	= 0
CTA_SECCTX_NAME		= 1
__CTA_SECCTX_MAX	= 2
CTA_SECCTX_MAX		= (__CTA_SECCTX_MAX - 1)

# enum ctattr_stats_cpu
class CtattrStatsCpu(Enum):
    CTA_STATS_UNSPEC		= 0
    CTA_STATS_SEARCHED		= 1
    CTA_STATS_FOUND		= 2
    CTA_STATS_NEW		= 3
    CTA_STATS_INVALID		= 4
    CTA_STATS_IGNORE		= 5
    CTA_STATS_DELETE		= 6
    CTA_STATS_DELETE_LIST	= 7
    CTA_STATS_INSERT		= 8
    CTA_STATS_INSERT_FAILED	= 9
    CTA_STATS_DROP		= 10
    CTA_STATS_EARLY_DROP	= 11
    CTA_STATS_ERROR		= 12
    CTA_STATS_SEARCH_RESTART	= 13
    __CTA_STATS_MAX		= 14
    CTA_STATS_MAX		= (__CTA_STATS_MAX - 1)
CTA_STATS_UNSPEC		= 0
CTA_STATS_SEARCHED		= 1
CTA_STATS_FOUND			= 2
CTA_STATS_NEW			= 3
CTA_STATS_INVALID		= 4
CTA_STATS_IGNORE		= 5
CTA_STATS_DELETE		= 6
CTA_STATS_DELETE_LIST		= 7
CTA_STATS_INSERT		= 8
CTA_STATS_INSERT_FAILED		= 9
CTA_STATS_DROP			= 10
CTA_STATS_EARLY_DROP		= 11
CTA_STATS_ERROR			= 12
CTA_STATS_SEARCH_RESTART	= 13
__CTA_STATS_MAX			= 14
CTA_STATS_MAX			= (__CTA_STATS_MAX - 1)

# enum ctattr_stats_global
class CtattrStatsGlobal(Enum):
    CTA_STATS_GLOBAL_UNSPEC	= 0
    CTA_STATS_GLOBAL_ENTRIES	= 1
    __CTA_STATS_GLOBAL_MAX	= 2
    CTA_STATS_GLOBAL_MAX	= (__CTA_STATS_GLOBAL_MAX - 1)
CTA_STATS_GLOBAL_UNSPEC		= 0
CTA_STATS_GLOBAL_ENTRIES	= 1
__CTA_STATS_GLOBAL_MAX		= 2
CTA_STATS_GLOBAL_MAX		= (__CTA_STATS_GLOBAL_MAX - 1)

# enum ctattr_expect_stats
class CtattrExpectStats(Enum):
    CTA_STATS_EXP_UNSPEC	= 0
    CTA_STATS_EXP_NEW		= 1
    CTA_STATS_EXP_CREATE	= 2
    CTA_STATS_EXP_DELETE	= 3
    __CTA_STATS_EXP_MAX		= 4
    CTA_STATS_EXP_MAX		= (__CTA_STATS_EXP_MAX - 1)
CTA_STATS_EXP_UNSPEC	= 0
CTA_STATS_EXP_NEW	= 1
CTA_STATS_EXP_CREATE	= 2
CTA_STATS_EXP_DELETE	= 3
__CTA_STATS_EXP_MAX	= 4
CTA_STATS_EXP_MAX	= (__CTA_STATS_EXP_MAX - 1)
