# Generated by h2py from ./h/linux/netfilter/nfnetlink_compat.h

from __future__ import absolute_import

NF_NETLINK_CONNTRACK_NEW = 0x00000001
NF_NETLINK_CONNTRACK_UPDATE = 0x00000002
NF_NETLINK_CONNTRACK_DESTROY = 0x00000004
NF_NETLINK_CONNTRACK_EXP_NEW = 0x00000008
NF_NETLINK_CONNTRACK_EXP_UPDATE = 0x00000010
NF_NETLINK_CONNTRACK_EXP_DESTROY = 0x00000020
NFNL_NFA_NEST = 0x8000
# H2PY_ERR: ./h/linux/netfilter/nfnetlink_compat.h - macro: def NFA_TYPE(attr): return ((attr)->nfa_type & 0x7fff)

# XXX:
# defined in nlstructs.nfnetlink_compat too
NFA_ALIGNTO = 4
def NFA_ALIGN(len): return (((len) + NFA_ALIGNTO - 1) & ~(NFA_ALIGNTO - 1))

# H2PY_ERR: ./h/linux/netfilter/nfnetlink_compat.h - macro: def NFA_LENGTH(len): return (NFA_ALIGN(sizeof(struct nfattr)) + (len))
def NFA_SPACE(len): return NFA_ALIGN(NFA_LENGTH(len))

# H2PY_ERR: ./h/linux/netfilter/nfnetlink_compat.h - macro: def NFA_DATA(nfa): return ((void *)(((char *)(nfa)) + NFA_LENGTH(0)))
# H2PY_ERR: ./h/linux/netfilter/nfnetlink_compat.h - macro: def NFA_PAYLOAD(nfa): return ((int)((nfa)->nfa_len) - NFA_LENGTH(0))
# H2PY_ERR: ./h/linux/netfilter/nfnetlink_compat.h - macro: def NFM_NFA(n): return ((struct nfattr *)(((char *)(n)) \
# H2PY_ERR: ./h/linux/netfilter/nfnetlink_compat.h - macro: def NFM_PAYLOAD(n): return NLMSG_PAYLOAD(n, sizeof(struct nfgenmsg))
